---
title: "Tarea_uno"
author: "Carlos Alarcon"
date: "23/9/2019"
output:
    html_document:
      fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Tarea 1

Genes desde un GRO-seq activados por Reelina.

## Visualización de los datos

```{r tarea1, fig.cap= "Figura1. Genes activados por Reelina"}
library(readxl)
List <- read_excel("C:/Users/cibal/OneDrive/Escritorio/Tarea R/Tarea1/List.xlsx", 
                   col_types = c("text", "text", "numeric", 
                                 "numeric"), skip = 1)
library(tidyverse)
library(dplyr)
List <- separate(List, c("Annotation"), "Name")
List$FDR <- log10(List$FDR)

library(ggplot2)
ggplot(List, aes(x = logFC, y = -FDR)) + geom_point(aes(color = Name)) + xlab("LogFC") + ylab("-log10 FDR") + theme_bw() + theme(legend.position = "none")
```

## Identificación de los genes rango -1 y 1 LogFC

```{r tarea 1}
library(readxl)
List <- read_excel("C:/Users/cibal/OneDrive/Escritorio/Tarea R/Tarea1/List.xlsx", 
                   col_types = c("text", "text", "numeric", 
                                 "numeric"), skip = 1)
library(tidyverse)
library(dplyr)
List <- separate(List, c("Annotation"), "Name")
List1 <- filter(List, logFC > -1) 
Listfiltrada <- filter(List1, logFC < 1)

library(kableExtra)
kable(Listfiltrada, digits = 5, caption = "Tabla Tarea 1. Genes filtrados activados por Reelina") %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```